image:
  file: .gitpod.Dockerfile
ports:
- port: 6080
  onOpen: notify
- port: 10000-20000
  onOpen: ignore
workspaceLocation: "."
tasks:
- command: start-vnc-session.sh
- command: gp await-port 6080 && gp preview $(gp url 6080)
- command: cd ${HOME} && wget https://raw.githubusercontent.com/icub-tech-iit/icub-setup-installation/master/.bashrc_iCub
- command: cd ~ && echo "if [ -f ~/.bashrc_iCub ]; then\n . ~/.bashrc_iCub\nfi" | cat - ~/.bashrc > temp && mv temp ~/.bashrc && rm temp && cd -
